# Import requirements for nRF9160 Feather Examples and Drivers
manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v2.4.2
      import:
        name-blocklist:
          - ant
          - azure-sdk-for-c
          - babblesim
          - cddl-gen
          - cirrus
          - cjson
          - cmock
          - dragoon
          - fatfs
          - find-my
          - homekit
          - loramac-node
          - lvgl
          - lz4
          - matter
          - mipi-sys-t
          - nrf-802154
          - openthread
          - sdk-hostap
          - unity
    # RTC Driver
    - name: pcf85063a
      url: https://github.com/circuitdojo/pcf85063a
      revision: master
      path: pcf85063a
  self:
    # This repository should be cloned to nrf9160-feather
    path: app
