# Import requirements for nRF9160 Feather Examples and Drivers
manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect

  projects:
    - name: nrf
      repo-path: sdk-nrf
      remote: ncs
      revision: v2.6.0
      import:
         name-allowlist:
          - cmsis
          - cmsis-dsp
          - cmsis-nn
          - hal_nordic
          - littlefs
          - mbedtls
          - mcuboot
          - nrf_hw_models
          - nrfxlib
          - picolibc
          - qcbor
          - segger
          - trusted-firmware-m
          - zcbor
          - zephyr

    # RTC Driver
    - name: pcf85063a
      url: https://github.com/circuitdojo/pcf85063a
      revision: master
      path: pcf85063a

  self:
    path: app
