name: Build Zephyr Docker Image
on:
  workflow_call:
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: '1'
    steps:
    - name: Build the Docker image
      run: |
        docker system prune --volumes -a -f
        docker build -f /docker-image-0.26.4/Dockerfile.ci https://github.com/zephyrproject-rtos/docker-image/archive/refs/tags/v0.26.4.tar.gz

    - name: Docker images
      run: docker images

    - name: Git checkout
      uses: actions/checkout@v3

    - name: Docker run
      uses: addnab/docker-run-action@v3
      with:
        image: zephyrproject-rtos/ci:v0.26.4
        options: -v ${{ github.workspace }}:${{ github.workspace }} -w ${{ github.workspace }} -e ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.16.1
        run: |
          west update
          west build -b circuitdojo_feather_nrf9160_ns ./app -p
