name: Build Test

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  get_zephyrprojectrtos_image:
      uses: ./.github/workflows/cache_zephyr_image.yml
      # with:
      #   image: zephyrprojectrtos/ci:v0.26.4

  build_app_test:
    needs: get_zephyrprojectrtos_image
    runs-on: ubuntu-latest
    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.16.1
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache/restore@v3
        id: docker-image-cache
        with:
          path: ~/docker_image_cache
          key: docker-image-cache-${{ runner.os }}

      - name: Docker Load
        if: ${{ steps.docker-image-cache.outputs.cache-hit == 'true' }}
        run: |
          docker load --input ~/docker_image_cache/zephyrprojectrtos-ci-v0.26.4.tar.gz
          docker image ls -a

      - name: West update
        run: west update

      - name: Build app circuitdojo_feather_nrf9160_ns
        run: west build -b circuitdojo_feather_nrf9160_ns ./app -p

      - name: Create build tarball
        run: |
          cd build
          tar czf merged.tar.gz build/zephyr/merged.hex

      - name: Upload tarball
        uses: actions/upload-artifact@v3
        with:
          name: build.tar.gz
          path: build/merged.tar.gz
