name: Cache Zephyr Docker Image

on:
  workflow_call:
  workflow_dispatch:

jobs:
  get_zephyrprojectrtos_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        id: docker-image-cache
        with:
          path: ~/docker_image_cache
          key: docker-image-cache-${{ runner.os }}

      - name: Update Docker Image Cache
        if: ${{ steps.docker-image-cache.outputs.cache-hit != 'true' }}
        run: |
          mkdir -p ~/docker_image_cache
          docker system prune --volumes -a -f
          docker pull ghcr.io/zephyrproject-rtos/ci:v0.26.4
          docker save ghcr.io/zephyrproject-rtos/ci:v0.26.4 | gzip  > ~/docker_image_cache/zephyrprojectrtos-ci-v0-26-4.tgz

      - uses: actions/cache/save@v3
        if: ${{ steps.docker-image-cache.outputs.cache-hit != 'true' }}
        with:
            path: ~/docker_image_cache
            key: ${{ steps.docker-image-cache.outputs.cache-primary-key }}
