name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag'
        required: true
        type: string
  workflow_call:
    inputs:
      version_tag:
        description: 'Version tag'
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    needs: build
    runs-on: ubuntu-latest

    env:
      version_tag: ${{ github.ref_type == 'tag' && github.ref_name || inputs.version_tag }}

    steps:
      - name: Download merged.hex
        uses: actions/download-artifact@v4
        with:
          name: merged.hex

      - name: Download app_update.bin
        uses: actions/download-artifact@v4
        with:
          name: app_update.bin

      - name: Upload merged.hex
        uses: svenstaro/upload-release-action@2.7.0
        with:
          tag: ${{ env.version_tag }}
          asset_name: merged-${{ env.version_tag }}.hex
          file: merged.hex
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload app_update.bin
        uses: svenstaro/upload-release-action@2.7.0
        with:
          tag: ${{ env.version_tag }}
          asset_name: app_update-${{ env.version_tag }}.bin
          file: app_update.bin
          repo_token: ${{ secrets.GITHUB_TOKEN }}
