name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag'
        required: true
        type: string

env:
  version_tag: ${{ inputs.version_tag || GITHUB_REF_NAME }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Load matching build tarball from cache
        uses: actions/cache/restore@v4
        with:
          path: build-${version_tag}.tar.xz
          key: build-${version_tag}.tar.xz

      - name: Seperate build files
        run: |
          tar -xf build-${version_tag}.tar.xz

      - name: Upload merged.hex.tar.xz
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: merged.hex.tar.xz
          path: merged.hex.tar.xz
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload app_update.bin.tar.xz
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: app_update.bin.tar.xz
          path: app_update.bin.tar.xz
          repo-token: ${{ secrets.GITHUB_TOKEN }}
