name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag'
        required: true
        type: string

jobs:
  release:
    env:
      version_tag: ${{ github.ref_type == 'tag' && github.ref_name || inputs.version_tag }}

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Load build cache
        uses: actions/cache/restore@v4
        with:
          path: |
            build/zephyr/merged-${{ env.version_tag }}.hex.tar.xz
            build/zephyr/app_update-${{ env.version_tag }}.bin.tar.xz
          key: build-${{ env.version_tag }}
          fail-on-cache-miss: true

      - name: Upload merged.hex
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: merged-${{ env.version_tag }}.hex.tar.xz
          path: build/zephyr/merged-${{ env.version_tag }}.hex.tar.xz
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload app_update.bin
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: app_update-${{ env.version_tag }}.bin.tar.xz
          path: build/zephyr/app_update-${{ env.version_tag }}.bin.tar.xz
          repo-token: ${{ secrets.GITHUB_TOKEN }}
