name: Release

on:
  release:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build.tar.xz
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Seperate build files
        run: |
          tar -xf build.tar.xz

      - name: Upload merged.hex.tar.xz
        uses: Shopify/upload-to-release@v2
        with:
          name: merged.hex.tar.xz
          path: merged.hex.tar.xz
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload app_update.bin.tar.xz
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: app_update.bin.tar.xz
          path: app_update.bin.tar.xz
          repo-token: ${{ secrets.GITHUB_TOKEN }}
